vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        bd:
            uri_prefix: /image
            upload_destination: '%kernel.project_dir%/public/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        categorie:
            uri_prefix: /image
            upload_destination: '%kernel.project_dir%/public/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer